DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'progress_status') THEN
        CREATE TYPE progress_status AS ENUM ('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', 'LOCKED');
    END IF;
END
$$;

CREATE TABLE IF NOT EXISTS course_enrollments
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT           NOT NULL,
    course_id             BIGINT           NOT NULL,
    status                progress_status  NOT NULL DEFAULT 'NOT_STARTED',
    progress_percent      NUMERIC(5, 2)    NOT NULL DEFAULT 0,
    completed_tasks_count INTEGER          NOT NULL DEFAULT 0,
    total_tasks_count     INTEGER          NOT NULL DEFAULT 0,
    total_score           INTEGER          NOT NULL DEFAULT 0,
    started_at            TIMESTAMP,
    completed_at          TIMESTAMP,
    last_activity_at      TIMESTAMP,
    created_at            TIMESTAMP        NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP        NOT NULL DEFAULT now(),
    CONSTRAINT uq_course_enrollments_user_course UNIQUE (user_id, course_id),
    CONSTRAINT chk_course_enrollments_progress_percent CHECK (progress_percent BETWEEN 0 AND 100),
    CONSTRAINT chk_course_enrollments_completed_tasks_count CHECK (completed_tasks_count >= 0),
    CONSTRAINT chk_course_enrollments_total_tasks_count CHECK (total_tasks_count >= 0),
    CONSTRAINT chk_course_enrollments_total_score CHECK (total_score >= 0)
);

CREATE INDEX IF NOT EXISTS idx_course_enrollments_user_id ON course_enrollments (user_id);
CREATE INDEX IF NOT EXISTS idx_course_enrollments_course_id ON course_enrollments (course_id);
CREATE INDEX IF NOT EXISTS idx_course_enrollments_status ON course_enrollments (status);

CREATE TABLE IF NOT EXISTS module_progress
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT           NOT NULL,
    course_id             BIGINT           NOT NULL,
    module_id             BIGINT           NOT NULL,
    status                progress_status  NOT NULL DEFAULT 'NOT_STARTED',
    progress_percent      NUMERIC(5, 2)    NOT NULL DEFAULT 0,
    completed_tasks_count INTEGER          NOT NULL DEFAULT 0,
    total_tasks_count     INTEGER          NOT NULL DEFAULT 0,
    score                 INTEGER          NOT NULL DEFAULT 0,
    started_at            TIMESTAMP,
    completed_at          TIMESTAMP,
    last_activity_at      TIMESTAMP,
    created_at            TIMESTAMP        NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP        NOT NULL DEFAULT now(),
    CONSTRAINT uq_module_progress_user_module UNIQUE (user_id, module_id),
    CONSTRAINT chk_module_progress_percent CHECK (progress_percent BETWEEN 0 AND 100),
    CONSTRAINT chk_module_progress_completed_tasks_count CHECK (completed_tasks_count >= 0),
    CONSTRAINT chk_module_progress_total_tasks_count CHECK (total_tasks_count >= 0),
    CONSTRAINT chk_module_progress_score CHECK (score >= 0)
);

CREATE INDEX IF NOT EXISTS idx_module_progress_user_course ON module_progress (user_id, course_id);
CREATE INDEX IF NOT EXISTS idx_module_progress_course_id ON module_progress (course_id);
CREATE INDEX IF NOT EXISTS idx_module_progress_module_id ON module_progress (module_id);
CREATE INDEX IF NOT EXISTS idx_module_progress_status ON module_progress (status);

CREATE TABLE IF NOT EXISTS task_progress
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT           NOT NULL,
    course_id          BIGINT           NOT NULL,
    module_id          BIGINT           NOT NULL,
    task_id            BIGINT           NOT NULL,
    status             progress_status  NOT NULL DEFAULT 'NOT_STARTED',
    attempts_count     INTEGER          NOT NULL DEFAULT 0,
    best_score         INTEGER          NOT NULL DEFAULT 0,
    last_score         INTEGER          NOT NULL DEFAULT 0,
    is_completed       BOOLEAN          NOT NULL DEFAULT FALSE,
    first_opened_at    TIMESTAMP,
    started_at         TIMESTAMP,
    first_success_at   TIMESTAMP,
    completed_at       TIMESTAMP,
    last_submission_at TIMESTAMP,
    last_activity_at   TIMESTAMP,
    created_at         TIMESTAMP        NOT NULL DEFAULT now(),
    updated_at         TIMESTAMP        NOT NULL DEFAULT now(),
    CONSTRAINT uq_task_progress_user_task UNIQUE (user_id, task_id),
    CONSTRAINT chk_task_progress_attempts_count CHECK (attempts_count >= 0),
    CONSTRAINT chk_task_progress_best_score CHECK (best_score >= 0),
    CONSTRAINT chk_task_progress_last_score CHECK (last_score >= 0)
);

CREATE INDEX IF NOT EXISTS idx_task_progress_user_module ON task_progress (user_id, module_id);
CREATE INDEX IF NOT EXISTS idx_task_progress_user_course ON task_progress (user_id, course_id);
CREATE INDEX IF NOT EXISTS idx_task_progress_task_id ON task_progress (task_id);
CREATE INDEX IF NOT EXISTS idx_task_progress_status ON task_progress (status);
CREATE INDEX IF NOT EXISTS idx_task_progress_is_completed ON task_progress (is_completed);
