CREATE TABLE IF NOT EXISTS task_submissions
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               BIGINT      NOT NULL,
    course_id             BIGINT      NOT NULL,
    module_id             BIGINT      NOT NULL,
    task_id               BIGINT      NOT NULL,
    submission_number     INTEGER     NOT NULL,
    language              VARCHAR(50) NOT NULL,
    source_code           TEXT        NOT NULL,
    status                VARCHAR(32) NOT NULL DEFAULT 'QUEUED',
    verdict               VARCHAR(32),
    score                 INTEGER     NOT NULL DEFAULT 0,
    passed_tests_count    INTEGER     NOT NULL DEFAULT 0,
    total_tests_count     INTEGER     NOT NULL DEFAULT 0,
    executor_request_id   VARCHAR(255),
    error_message         TEXT,
    submitted_at          TIMESTAMP   NOT NULL DEFAULT now(),
    started_at            TIMESTAMP,
    finished_at           TIMESTAMP,
    created_at            TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at            TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT uq_task_submissions_user_task_number UNIQUE (user_id, task_id, submission_number)
);

ALTER TABLE task_submissions ADD COLUMN IF NOT EXISTS status VARCHAR(32);
ALTER TABLE task_submissions ADD COLUMN IF NOT EXISTS score INTEGER;
ALTER TABLE task_submissions ADD COLUMN IF NOT EXISTS passed_tests_count INTEGER;
ALTER TABLE task_submissions ADD COLUMN IF NOT EXISTS total_tests_count INTEGER;
ALTER TABLE task_submissions ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP;
ALTER TABLE task_submissions ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
ALTER TABLE task_submissions ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;

UPDATE task_submissions
SET status = CASE
                 WHEN finished_at IS NULL THEN 'RUNNING'
                 ELSE 'FINISHED'
    END
WHERE status IS NULL;

UPDATE task_submissions SET score = 0 WHERE score IS NULL;
UPDATE task_submissions SET passed_tests_count = 0 WHERE passed_tests_count IS NULL;
UPDATE task_submissions SET total_tests_count = 0 WHERE total_tests_count IS NULL;
UPDATE task_submissions SET submitted_at = now() WHERE submitted_at IS NULL;
UPDATE task_submissions SET created_at = now() WHERE created_at IS NULL;
UPDATE task_submissions SET updated_at = now() WHERE updated_at IS NULL;

ALTER TABLE task_submissions ALTER COLUMN status SET DEFAULT 'QUEUED';
ALTER TABLE task_submissions ALTER COLUMN score SET DEFAULT 0;
ALTER TABLE task_submissions ALTER COLUMN passed_tests_count SET DEFAULT 0;
ALTER TABLE task_submissions ALTER COLUMN total_tests_count SET DEFAULT 0;
ALTER TABLE task_submissions ALTER COLUMN submitted_at SET DEFAULT now();
ALTER TABLE task_submissions ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE task_submissions ALTER COLUMN updated_at SET DEFAULT now();

ALTER TABLE task_submissions ALTER COLUMN status SET NOT NULL;
ALTER TABLE task_submissions ALTER COLUMN score SET NOT NULL;
ALTER TABLE task_submissions ALTER COLUMN passed_tests_count SET NOT NULL;
ALTER TABLE task_submissions ALTER COLUMN total_tests_count SET NOT NULL;
ALTER TABLE task_submissions ALTER COLUMN submitted_at SET NOT NULL;
ALTER TABLE task_submissions ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE task_submissions ALTER COLUMN updated_at SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_submissions_score') THEN
        ALTER TABLE task_submissions
            ADD CONSTRAINT chk_task_submissions_score CHECK (score >= 0) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_submissions_passed_tests_count') THEN
        ALTER TABLE task_submissions
            ADD CONSTRAINT chk_task_submissions_passed_tests_count CHECK (passed_tests_count >= 0) NOT VALID;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_task_submissions_total_tests_count') THEN
        ALTER TABLE task_submissions
            ADD CONSTRAINT chk_task_submissions_total_tests_count CHECK (total_tests_count >= 0) NOT VALID;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_task_submissions_user_task
    ON task_submissions (user_id, task_id);

CREATE INDEX IF NOT EXISTS idx_task_submissions_user_task_submission_number
    ON task_submissions (user_id, task_id, submission_number);

CREATE INDEX IF NOT EXISTS idx_task_submissions_task_id
    ON task_submissions (task_id);

CREATE INDEX IF NOT EXISTS idx_task_submissions_status
    ON task_submissions (status);

CREATE TABLE IF NOT EXISTS submission_test_results
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_id      BIGINT       NOT NULL,
    test_key           VARCHAR(255) NOT NULL,
    test_order         INTEGER      NOT NULL,
    status             VARCHAR(32)  NOT NULL DEFAULT 'SKIPPED',
    input_snapshot     TEXT,
    expected_output    TEXT,
    actual_output      TEXT,
    error_output       TEXT,
    execution_time_ms  INTEGER,
    memory_kb          INTEGER,
    created_at         TIMESTAMP    NOT NULL DEFAULT now(),
    CONSTRAINT uq_submission_test_results_submission_order UNIQUE (submission_id, test_order)
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'submission_test_results'
          AND column_name = 'testkey'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'submission_test_results'
          AND column_name = 'test_key'
    ) THEN
        ALTER TABLE submission_test_results RENAME COLUMN testkey TO test_key;
    END IF;
END
$$;

ALTER TABLE submission_test_results ADD COLUMN IF NOT EXISTS status VARCHAR(32);
ALTER TABLE submission_test_results ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;

UPDATE submission_test_results SET status = 'SKIPPED' WHERE status IS NULL;
UPDATE submission_test_results SET created_at = now() WHERE created_at IS NULL;

ALTER TABLE submission_test_results ALTER COLUMN status SET DEFAULT 'SKIPPED';
ALTER TABLE submission_test_results ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE submission_test_results ALTER COLUMN status SET NOT NULL;
ALTER TABLE submission_test_results ALTER COLUMN created_at SET NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_submission_test_results_test_order') THEN
        ALTER TABLE submission_test_results
            ADD CONSTRAINT chk_submission_test_results_test_order CHECK (test_order >= 0) NOT VALID;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_submission_test_results_submission_id
    ON submission_test_results (submission_id);

CREATE INDEX IF NOT EXISTS idx_submission_test_results_submission_test_key
    ON submission_test_results (submission_id, test_key);

CREATE INDEX IF NOT EXISTS idx_submission_test_results_status
    ON submission_test_results (status);
